### ISSUE TITLE
Bug: Unable to re-run script after creating a class that inherits from base

### ISSUE THREAD

**Issue by cslotboom** [specklesystems/specklepy#359]
When inheriting from base, I am unable to run a script twice without getting a value error my custom class. Looks like some persistent global registry object isn't getting properly refreshed on each run?

I'm creating the object below, and I get this error when running twice:

```Python

class PointGroup(Base, speckle_type="UserObject"):
    
    def __init__(self, points:list[Node], lines:list[Element2D] = None):
        self.points = points
        self.lines = lines

```

![image](https://github.com/user-attachments/assets/d5a8e390-0f0c-43a9-9c8a-53d77515df48)

## System Info
WIndows 11,
specklepy = 2.21

**Comment by gjedlicska** [comment]
Hey @cslotboom, it would be nice to understand where you are running this script. The execution environment is probably trying to re-parse your code in a running environment.

I can only reproduce this in a plain python script by registering the same class in 2 different places:
```python
from specklepy.objects.base import Base
from specklepy.objects.structural.geometry import Element2D, Node


class PointGroup(Base, speckle_type="UserObject"):
     
    def __init__(self, points:list[Node], lines:list[Element2D] = None):
        self.points = points
        self.lines = lines



class PointGroup(Base, speckle_type="UserObject"):
     
    def __init__(self, points:list[Node], lines:list[Element2D] = None):
        self.points = points
        self.lines = lines
```

produces the same error
```
Traceback (most recent call last):
  File "/home/gergojedlicska/Speckle/specklepy/example/register.py", line 13, in <module>
    class PointGroup(Base, speckle_type="UserObject"):
  File "/home/gergojedlicska/Speckle/specklepy/src/specklepy/objects/base.py", line 174, in __init_subclass__
    raise ValueError(
ValueError: The speckle_type: UserObject is already registered for type: PointGroup. Please choose a different type name.
```

so most probably this is what is happening in your scripting environment. Ideally this situation would be avoided, by only running the class definition once on startup, cause we have no extensive check to make sure the two type definitions match 1-1.

If you override the type definition with some differences, things can get weird unexpectedly

**Comment by cslotboom** [comment]
Oops, I never saw your response. I was running my code using ipython in the spyder IDE. It's common to have one python kernel active and keep rerunning each script using that kernel. There might be some reloading weirdness that happens at the start of each script run.

It is definitely annoying to start a new kernel for each run, but that is the current solution.
